### ISSUE TITLE
Error in ComfyUI log

### ISSUE THREAD

**Issue by fafayqa** [florestefano1975/ComfyUI-CogVideoX#6]
I got this error in ComfyUI log:

Traceback (most recent call last):
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2075, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoX\__init__.py", line 12, in <module>
    from diffusers import (
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py). Did you mean: 'hf_hub_download'?

Cannot import Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoX module for custom nodes: cannot import name 'cached_download' from 'huggingface_hub' (Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py)

**Comment by fafayqa** [comment]
So, I was able solving the above error by removing import of "cached_download" from huggingface_hub_init_.py.

But now new error in the ComfyUI log appears:

Traceback (most recent call last):
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2075, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoX\__init__.py", line 12, in <module>
    from diffusers import (
ImportError: cannot import name 'CogVideoXPipeline' from 'diffusers' (Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py)

Cannot import Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoX module for custom nodes: cannot import name 'CogVideoXPipeline' from 'diffusers' (Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py)

WHAT NOW - HOW TO SOLVE THIS?

**Comment by fafayqa** [comment]
SOLVED by updating the python diffusers to their latest version. :-)

**Comment by fafayqa** [comment]
SOLVED by updating the python diffusers to their latest version. :-)
